/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AIR;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rofiq
 */
public class addFlight extends javax.swing.JFrame {

    /**
     * Creates new form addFlight2
     */
    public addFlight() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        autoID();
        background.setIcon(new javax.swing.ImageIcon("src/main/java/resource/background.jpg"));
        jPanel1.setBackground(new Color(255,255,255,160));
        txtflightid.setEditable(false);
    }
    
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jflightname = new javax.swing.JLabel();
        jsource = new javax.swing.JLabel();
        jdeparture = new javax.swing.JLabel();
        txtflightname = new javax.swing.JTextField();
        jdate = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jdtime = new javax.swing.JLabel();
        txtdtime = new javax.swing.JTextField();
        jarrtime = new javax.swing.JLabel();
        txtarrtime = new javax.swing.JTextField();
        jflightcharge = new javax.swing.JLabel();
        txtflightcharge = new javax.swing.JTextField();
        txtsource = new javax.swing.JComboBox<>();
        txtdeparture = new javax.swing.JComboBox<>();
        txtflightid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"AIR\" Airline Reservation System");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flight ID");

        jflightname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jflightname.setForeground(new java.awt.Color(255, 255, 255));
        jflightname.setText("Flight Name");

        jsource.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jsource.setForeground(new java.awt.Color(255, 255, 255));
        jsource.setText("Source");

        jdeparture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdeparture.setForeground(new java.awt.Color(255, 255, 255));
        jdeparture.setText("Departure");

        txtflightname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdate.setForeground(new java.awt.Color(255, 255, 255));
        jdate.setText("Date");

        jdtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jdtime.setForeground(new java.awt.Color(255, 255, 255));
        jdtime.setText("Dep Time");

        txtdtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jarrtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jarrtime.setForeground(new java.awt.Color(255, 255, 255));
        jarrtime.setText("Arr Time");

        txtarrtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jflightcharge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jflightcharge.setForeground(new java.awt.Color(255, 255, 255));
        jflightcharge.setText("Flight Charge");

        txtflightcharge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtflightcharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtflightchargeActionPerformed(evt);
            }
        });

        txtsource.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Jakarta", "Bengkulu", "Lampung", "Cilacap", "Makasar", "Bali" }));
        txtsource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsourceActionPerformed(evt);
            }
        });

        txtdeparture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Jakarta", "Bengkulu", "Lampung", "Cilacap", "Makasar", "Bali" }));
        txtdeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepartureActionPerformed(evt);
            }
        });

        txtflightid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jflightname)
                    .addComponent(jsource)
                    .addComponent(jdeparture))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtdeparture, 0, 158, Short.MAX_VALUE)
                    .addComponent(txtsource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtflightname)
                    .addComponent(txtflightid))
                .addGap(382, 382, 382)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate)
                    .addComponent(jarrtime)
                    .addComponent(jflightcharge)
                    .addComponent(jdtime))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtdtime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtflightcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtarrtime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtflightid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdate))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtflightname)
                    .addComponent(jflightname)
                    .addComponent(txtdtime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdtime))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsource)
                    .addComponent(txtsource, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtarrtime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jarrtime))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdeparture)
                    .addComponent(txtdeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtflightcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jflightcharge))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(77, 38, 1230, 315);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(970, 590, 125, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1170, 590, 125, 60);
        getContentPane().add(background);
        background.setBounds(0, 0, 1360, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void autoID(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MAX(id) from flight");
            rs.next();
            rs.getString("MAX(id)");
            if(rs.getString("MAX(id)") == null){
                txtflightid.setText("F0001");
            }else {
                long id = Long.parseLong(rs.getString("MAX(id)").substring(2,rs.getString("MAX(id)").length()));
                id++;
                 txtflightid.setText("F0" + String.format("%03d", id));
                
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void txtsourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsourceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = txtflightid.getText();
        String flightname = txtflightname.getText();

        String source = txtsource.getSelectedItem().toString().trim();
        String depart = txtdeparture.getSelectedItem().toString().trim();

        DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
        

        String departtime = txtdtime.getText();
        String arrtime = txtarrtime.getText();
        String flightcharge = txtflightcharge.getText();

        boolean emptyFields = (
                flightname.equals("") || source.equals("None") || depart.equals("None") ||
                departtime.equals("") || arrtime.equals("") || flightcharge.equals("")
                );
        
        if(emptyFields) {
                JOptionPane.showMessageDialog(null, "Please fill all forms!");

                }else {
            String date = da.format(txtdate.getDate());
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            pst = con.prepareStatement("insert into flight(id,flightname,source,depart,date,deptime,arrtime,flightcharge)values(?,?,?,?,?,?,?,?)");

            pst.setString(1, id);
            pst.setString(2, flightname);
            pst.setString(3, source);
            pst.setString(4, depart);
            pst.setString(5, date);
            pst.setString(6, departtime);
            pst.setString(7, arrtime);
            pst.setString(8, flightcharge);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Flight Created!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepartureActionPerformed

    private void txtflightchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtflightchargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtflightchargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jarrtime;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jdeparture;
    private javax.swing.JLabel jdtime;
    private javax.swing.JLabel jflightcharge;
    private javax.swing.JLabel jflightname;
    private javax.swing.JLabel jsource;
    private javax.swing.JTextField txtarrtime;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txtdeparture;
    private javax.swing.JTextField txtdtime;
    private javax.swing.JTextField txtflightcharge;
    private javax.swing.JTextField txtflightid;
    private javax.swing.JTextField txtflightname;
    private javax.swing.JComboBox<String> txtsource;
    // End of variables declaration//GEN-END:variables
}
